//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_Reservation_New
{
    using System;
    using System.Collections.Generic;
    
    public partial class Train_Schedules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Train_Schedules()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int schedule_id { get; set; }
        public Nullable<int> train_id { get; set; }
        public Nullable<int> station_id { get; set; }
        public Nullable<System.DateTime> arrival_time { get; set; }
        public Nullable<System.DateTime> departure_time { get; set; }
        public Nullable<int> stop_number { get; set; }
        public Nullable<System.DateTime> journey_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual Station Station { get; set; }
        public virtual Train Train { get; set; }
    }
}
